# Generated by Django 3.2.5 on 2021-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_image', models.ImageField(blank=True, default='user_default', null=True, upload_to='prof_image', verbose_name='Profile Image')),
            ],
        ),
    ]
