# Generated by Django 3.2.5 on 2021-08-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_p_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='P_image',
            field=models.ImageField(blank=True, null=True, upload_to='prof_image/%Y/%m/%d', verbose_name='Profile Image'),
        ),
    ]
